### ISSUE TITLE
Camelcasing of names breaks firebase key references

### ISSUE THREAD

**Issue by davidLeonardi** [dsdenes/firebase-denormalizer#1]
In the case of denormalizing something like:
users and  a generated key such as Esu3u2837293uhd, the generated pathname will be lowercased incorrectly:
esu3u2837293uhdUsers , resulting in id lookup fails and eventual id normalziation which defeats having unique ID's.
As such, i'd rather propose using dashes, so the result would be Esu3u2837293uhd-users .

**Comment by dsdenes** [comment]
Good point, thank you for the report. Please have a look at the new Readme.

https://github.com/dsdenes/firebase-denormalizer/releases/tag/2.0.0
